import getConfig from 'next/config';
import Head from 'next/head';
import styles from '../styles/pages/Home.module.scss';
import PostCard from '../src/components/PostCard/PostCard';
import { withRouter } from 'next/router';
import { useContext, useEffect, useState } from 'react';
import helpers from '../src/helpers';
import { buildHTML } from '../src/MarkdownLayer.mjs';
import matter from 'gray-matter';
import remarkBreaks from 'remark-breaks'
import { HeaderContext } from './_app';
import TagButton from '../src/components/TagButton/TagButton';

function Home(props) {
    const { posts, tags = [], router } = props;
    const [postList, setPostList] = useState([]);
    const [tagsList, setTagsList] = useState([]);

    const [_,setHeaderState] = useContext(HeaderContext);

    useEffect(() => {
        setHeaderState(old => ({
            ...old,
            tags: [],
            title: undefined
        }));
    }, []);

    useEffect(() => {
        if (!router.isReady) return;
        const { tags: tagsQuery } = router.query;

        let updateList = [];
        if (tagsQuery) {
            const tagsArr = tagsQuery.split(',');
            setTagsList(tagsArr);
            updateList = posts.filter(({tags}) => tagsArr.some(t => tags.includes(t)))
        }

        setPostList(() => updateList.length === 0 ? posts : updateList);
    }, [router, posts]);

    const updateQuery = (tag) => {
        const newQuery = `/?tags=${[...tagsList,tag].join(',')}`;
        router.push(newQuery, newQuery, {
            shallow: true
        })
    }

    const removeFromQuery = (tag) => {
        const copyTagList = JSON.parse(JSON.stringify(tagsList));
        copyTagList.splice(copyTagList.indexOf(tag),1);
        
        const newRoute = copyTagList.length === 0 ? '/' : `/?tags=${copyTagList.join(',')}`;
        router.push(newRoute, newRoute, {
            shallow: true
        });

        setTagsList(copyTagList);
    }

    return (
        <>
            <Head>
                <title>Jake Bukuts Blog</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles['home__tag-container']}>
                <h2>Filter by tags</h2>
                <div>
                    {tags.map((tag,i) => {
                        const isActive = tagsList.includes(tag);
                        const tagProps = [
                            {onClick: () => updateQuery(tag)},
                            {isActive: true, onClick: () => removeFromQuery(tag)}
                        ];

                        return <TagButton key={i} text={tag} {...tagProps[+isActive]}/>
                    })}
                </div>
            </div>

            <div className={styles['home__post-container']}>
                {postList.map((post, i) => (
                    <PostCard key={i} {...post}/>
                ))}
            </div>
        </>
    )
}

export default withRouter(Home);

export async function getStaticProps() {
    const { serverRuntimeConfig } = getConfig();
    const { mdLayer: { allGistData } } = serverRuntimeConfig;
    const allGists = await Promise.all(allGistData.map(async (post) => {
        const { download_url } = post;
        
        const rawText = await fetch(download_url).then(r => r.text());
        const data = matter(rawText, { excerpt: true, excerpt_separator: '<!--- end preview -->' });
        const { data: frontmatter, excerpt } = data;

        return {
            ...post,
            excerpt: await buildHTML(excerpt, [remarkBreaks]),
            ...frontmatter
        }
    }));

    const tags = [...new Set(allGists.reduce((acc, {tags}) => [...acc, ...tags] , []))].sort();

    return {
        props: { 
            posts: allGists,
            tags
        }
    }
}