import getConfig from 'next/config';
import Head from 'next/head';
import styles from '../styles/Home.module.scss';
import PostCard from '../src/components/PostCard';
import { withRouter } from 'next/router';
import { useEffect, useState } from 'react';
import VirtualScroll from '../src/components/VirtualScroll';

function Home(props) {
    const { posts, tags = [], router } = props;
    const [postList, setPostList] = useState([]);
    const [tagsList, setTagsList] = useState([]);

    useEffect(() => {
        if (!router.isReady) return;
        const { tags: tagsQuery } = router.query;
        const queryRegex = /^(\w+,?)+\w+$/g;

        let updateList = [];
        if (tagsQuery && queryRegex.test(tagsQuery)) {
            const tagsArr = tagsQuery.split(',');
            setTagsList(tagsArr);
            updateList = posts.filter(({tags}) => tagsArr.some(t => tags.includes(t)))
        }

        setPostList(() => updateList.length === 0 ? posts : updateList);
    }, [router, posts]);

    const updateQuery = (tag) => {
        const newQuery = `/?tags=${[...tagsList,tag].join(',')}`;
        router.push(newQuery, newQuery, {
            shallow: true
        })
    }

    const removeFromQuery = (tag) => {
        const copyTagList = JSON.parse(JSON.stringify(tagsList));
        copyTagList.splice(copyTagList.indexOf(tag),1);
        
        const newRoute = copyTagList.length === 0 ? '/' : `/?tags=${copyTagList.join(',')}`;
        router.push(newRoute, newRoute, {
            shallow: true
        });

        setTagsList(copyTagList);
    }

    return (
        <>
            <Head>
                <title>Jake Bukuts Blog</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1 style={{marginTop: '0px'}}>Welcome to the Blog</h1>
            <div className={styles['home__tag-container']}>
                {tags.map((tag,i) => {
                    const isActive = tagsList.includes(tag);
                    return  <button 
                        style={{ background: isActive ? 'red' : ''}} 
                        onClick={() => isActive ? removeFromQuery(tag) : updateQuery(tag)} key={i}>
                            {tag}
                    </button>
                })}
            </div>
            <VirtualScroll rowHeight={180} nodePadding={2}>
                {postList.map((post, i) => (
                    <PostCard key={i} {...post}/>
                ))}
            </VirtualScroll>
        </>
    )
}

export default withRouter(Home);

export async function getStaticProps() {
    const { serverRuntimeConfig } = getConfig();
    const { mdLayer } = serverRuntimeConfig;
    const allGists = JSON.parse(JSON.stringify(mdLayer.allGistData));
    const tags = [...new Set(allGists.reduce((acc, {tags}) => [...acc, ...tags] , []))].sort();

    allGists.forEach(post => {
        delete post.content;
        delete post.title;
        delete post.sha;
    });

    return {
        props: { 
            posts: allGists,
            tags
        }
    }
}